[package]
name = "shanebutt/eos"
version = "0.1.0-ui.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Flipper = "reselim/flipper@2.0.0"
Roact = "roblox/roact@1.4.2"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
RoactFlipper = "reselim/roact-flipper@1.1.0"
Llama = "shanebutt/llama@1.1.0"
TestEZ = "roblox/testez@0.4.1"

[server-dependencies]
RobaseService = "shanebutt/robase-service@2.2.1"