-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	[".icons"] = {
		PowerOff = {
			[".icon"] = "rbxassetid://7370269083",
			[".icon-drop-shadow-dark"] = "rbxassetid://7370268867",
			[".icon-drop-shadow-light"] = "rbxassetid://7370269005",
		},
		PowerOff2 = {
			[".icon"] = "rbxassetid://7397658565",
			[".icon-drop-shadow-dark"] = "rbxassetid://7397658287",
			[".icon-drop-shadow-light"] = "rbxassetid://7397658433",
		},
		Teams = {
			[".icon"] = "rbxassetid://7397658935",
			[".icon-drop-shadow-dark"] = "rbxassetid://7397658722",
			[".icon-drop-shadow-light"] = "rbxassetid://7397658844",
		},
	},
	Neumorphic = {
		Buttons = {
			["Hexagon v2"] = {
				[".drop-shadow-dark"] = "rbxassetid://7370269198",
				[".drop-shadow-light"] = "rbxassetid://7370269264",
				[".shape-fill"] = "rbxassetid://7370269326",
				[".states"] = {
					[".pressed"] = {
						[".inner-shadow-dark"] = "rbxassetid://7370269446",
						[".inner-shadow-light"] = "rbxassetid://7370269642",
					},
				},
			},
		},
	},
}